name: togglTool
description: Tool for downloading toogl data
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.0.2
  built_value_generator: ^8.0.5
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^5.0.7
